#' Calculate d13C isoscape
#'
#' Applies simple mixing model to percent vegetation cover layers generated by
#'   \code{calcPFTCover} or \code{calcC4Ratio}. User provides d13C endmember
#'   values for each input plant functional type. Function may also be applied
#'   to another endmember statistic, e.g., input endmember standard deviation
#'   to generate an "uncertainty" layer.
#'
#' @param pft.cover RasterBrick. Percent cover for each plant functional type,
#'   may be result of \code{calcPFTCover}.
#' @param d13C.embs Numeric. Vector of length equal to number of layers in
#'   \code{pft.cover}. Values correspond to d13C endmembers for each
#'   \code{pft.cover} vegetation type.
#' @param scale Integer. Scale factor for vegetation cover values. Default
#'   value = 100.
#' @param filename Character. Optional output root filename passed to
#'   \code{writeRaster}, default output file type is GeoTiff. If not specified,
#'   output is written to a temporary file.
#' @param ... Other arguments passed to \code{writeRaster}.
#' @return RasterLayer. Values correspond to mean vegetation d13C (per mil) for
#'   each grid cell.
#' @export
#' @examples \donttest{# User provides vector of d13C endmembers corresponding to input vegetation layers
#' d13C_emb <- c(-12.5, -26.7, -27.0)  # C4 herb, C3 herb, Woody
#'
#' # Generate d13C isoscape
#' d13C_iso <- calcDel13C(pft_cover, d13C_emb)
#'
#' # Plot d13C isoscape
#' plot(d13C_iso)}
#'
#' \donttest{# Calculate weighted standard deviation of mean d13C value
#' d13C_emb_std <- c(1.1, 2.3, 1.7)  # endmember std.dev.
#' d13C_iso_std <- calcDel13C(pft_cover, d13C_std)
#'
#' # Plot standard deviation layer
#' plot(d13C_iso_std)}
#' @seealso \link[grassmapr]{calcPFTCover}, \link[grassmapr]{calcC4Ratio},
#'   \link[raster]{overlay}.
#'
calcDel13C <- function(pft.cover, d13C.embs, scale = 100, filename = "", ...) {

  # Calculates d13C isoscape, given input vegetation percent cover by plant
  #   functional type and vector array of endmember values.

  # Error check: Length of C4.flag vector equals nlayers for veg.layers stack
  if(length(d13C.embs) != nlayers(pft.cover)) {
    stop("Length of d13C.embs vector does not equal nlayers in pft.cover")
  }

  if(filename != "") {
    outfile <- paste0(trim(filename), ".tif")
    overlay(calc(pft.cover, function(x) x*d13C.embs/scale), fun = "sum",
      outfile, format = "GTiff", datatype = "INT2U", overwrite = TRUE)
  } else {
    d13C_iso <- overlay(calc(pft.cover, function(x) x*d13C.embs/scale),
      fun = "sum")
    return(d13C_iso)
  }
}

